server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
    username: caidt
    password: 257701
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # Additional native properties to set on the JPA provider.
    properties:
      # 用法见userJpa, 可以给jpa里面添加自定义方法，在postfix=impl后缀的实现即可调用，无须继承
      repository-impl-postfix: impl
      sessionFactory: org.springframework.orm.hibernate4.LocalSessionFactoryBean
      hibernate:
        dialect:
          store_engine: innodb

    mapping-resources: classpath:hibernate.xml

  redis:
    host: 192.168.199.240
    port: 6379
    password: caidt

    jedis:
      pool:
        max-active: 60
        max-idle: 30
        max-wait: 1000
    timeout: 0

#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#  thymeleaf:
#    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 3000
    cache-enabled: true
    use-generated-keys: true



logging:
  config: classpath:logback.xml
  path: logs/




---
# 自定义配置
student:
  name: caidt
  age:  26
...