server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
    username: caidt
    password: 257701
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  #    schema: classpath:schema.sql
  #    data: classpath:data.sql

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # Additional native properties to set on the JPA provider.
    properties:
      # 用法见userJpa, 可以给jpa里面添加自定义方法，在postfix=impl后缀的实现即可调用，无须继承
      repository-impl-postfix: impl
      sessionFactory: org.springframework.orm.hibernate4.LocalSessionFactoryBean
      hibernate:
        dialect:
          storage_engine: innodb

    mapping-resources: classpath:hibernate.cfg.xml

  redis:
    host: 192.168.199.240
    port: 6379
    password: caidt

    #    jedis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    timeout: 0

#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#  thymeleaf:
#    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 3000
    cache-enabled: true
    use-generated-keys: true



logging:
  config: classpath:logback.xml
  path: logs/

  level:
    com.example.spring.service: debug



#---
#spring:
#  profiles: test
#  # 数据库配置
#  datasource:
#    url: jdbc:h2:mem:test
#    username: root
#    password: 123456
#    driver-class-name: org.h2.Driver
#    schema: classpath:schema.sql
#    data: classpath:data.sql
#...


---
# 自定义配置
student:
  name: caidt
  age:  26
...