server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
    username: caidt
    password: 257701
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # Additional native properties to set on the JPA provider.
    properties:
      sessionFactory: org.springframework.orm.hibernate4.LocalSessionFactoryBean
      hibernate:
        dialect:
          store_engine: innodb

    mapping-resources: classpath:hibernate.xml

#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
#  thymeleaf:
#    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 3000
    cache-enabled: true
    use-generated-keys: true



logging:
  config: classpath:logback.xml
  path: logs/




---
# 自定义配置
student:
  name: caidt
  age:  26
...